#!/usr/bin/env python3

import unittest

from validate_pr_body import validate


GOOD_BODY = """## How to Review

Read `internal/widget.go` first and verify failures remain closed.

## Summary

Adds the requested widget behavior without changing the public API.

## Testing

- `go test ./...` — passed

## Live Evidence

Tested against the development deployment:

```console
$ curl -fsS https://example.test/widgets/73
{"status":"enabled"}
```

## Example Usage

```yaml
widget: enabled
```

Closes #73
"""

BUGBOT_SUMMARY = """<!-- CURSOR_SUMMARY -->
> [!NOTE]
> **Low Risk**
> Documentation-only change.
>
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit abc123.</sup>
<!-- /CURSOR_SUMMARY -->"""


class ValidatePRBodyTest(unittest.TestCase):
    def test_accepts_complete_body(self) -> None:
        self.assertEqual(validate(GOOD_BODY, issue=73, require_example=True), [])

    def test_requires_core_sections(self) -> None:
        errors = validate("## Summary\n\nChange.\n")
        self.assertIn("expected exactly one ## How to Review heading", errors)
        self.assertIn("expected exactly one ## Testing heading", errors)

    def test_requires_core_section_order(self) -> None:
        body = "## Summary\n\nChange.\n## How to Review\n\nRead.\n## Testing\n\nPassed.\n"
        self.assertIn(
            "required sections must be ordered: How to Review, Summary, Testing",
            validate(body),
        )

    def test_requires_example_when_requested(self) -> None:
        body = GOOD_BODY.replace("## Example Usage\n\n```yaml\nwidget: enabled\n```\n\n", "")
        self.assertIn(
            "expected exactly one ## Example Usage heading",
            validate(body, require_example=True),
        )

    def test_requires_live_evidence_when_requested(self) -> None:
        body = GOOD_BODY.replace(
            '## Live Evidence\n\nTested against the development deployment:\n\n'
            '```console\n$ curl -fsS https://example.test/widgets/73\n'
            '{"status":"enabled"}\n```\n\n',
            "",
        )
        self.assertIn(
            "expected exactly one ## Live Evidence heading",
            validate(body, require_live_evidence=True),
        )

    def test_live_evidence_requires_image_or_transcript(self) -> None:
        body = GOOD_BODY.replace(
            'Tested against the development deployment:\n\n'
            '```console\n$ curl -fsS https://example.test/widgets/73\n'
            '{"status":"enabled"}\n```',
            "Observed the expected result.",
        )
        self.assertIn(
            "## Live Evidence must contain an embedded image or fenced transcript",
            validate(body, require_live_evidence=True),
        )

    def test_accepts_embedded_live_screenshot(self) -> None:
        body = GOOD_BODY.replace(
            'Tested against the development deployment:\n\n'
            '```console\n$ curl -fsS https://example.test/widgets/73\n'
            '{"status":"enabled"}\n```',
            "Development deployment after enabling the widget.\n\n"
            "![Enabled widget in the deployment UI](https://example.test/evidence.png)",
        )
        self.assertEqual(validate(body, require_live_evidence=True), [])

    def test_rejects_ai_attribution(self) -> None:
        variants = (
            "<!-- CURSOR_SUMMARY -->",
            "Generated by Claude",
            "Generated using ChatGPT",
            "Co-authored-by: Codex <bot@example.com>",
            "Reviewed by Cursor Bugbot",
        )
        for variant in variants:
            with self.subTest(variant=variant):
                self.assertTrue(validate(f"{GOOD_BODY}\n{variant}\n"))

    def test_accepts_exactly_preserved_ending_bugbot_summary(self) -> None:
        existing_body = f"Old description.\n\n{BUGBOT_SUMMARY}\n"
        rewritten_body = f"{GOOD_BODY}\n{BUGBOT_SUMMARY}\n"
        self.assertEqual(
            validate(rewritten_body, issue=73, existing_body=existing_body), []
        )

    def test_rejects_changed_ending_bugbot_summary(self) -> None:
        existing_body = f"Old description.\n\n{BUGBOT_SUMMARY}\n"
        rewritten_body = f"{GOOD_BODY}\n{BUGBOT_SUMMARY.replace('abc123', 'def456')}\n"
        self.assertIn(
            "ending Bugbot summary must be preserved exactly",
            validate(rewritten_body, issue=73, existing_body=existing_body),
        )

    def test_rejects_removed_ending_bugbot_summary(self) -> None:
        existing_body = f"Old description.\n\n{BUGBOT_SUMMARY}\n"
        self.assertIn(
            "ending Bugbot summary must be preserved exactly",
            validate(GOOD_BODY, issue=73, existing_body=existing_body),
        )

    def test_rejects_new_bugbot_summary_without_existing_source(self) -> None:
        self.assertIn(
            "Bugbot summary must come unchanged from the existing PR body",
            validate(f"{GOOD_BODY}\n{BUGBOT_SUMMARY}\n", issue=73),
        )

    def test_requires_exact_closing_trailer(self) -> None:
        errors = validate(GOOD_BODY.replace("Closes #73", "Fixes #73"), issue=73)
        self.assertIn("expected exactly one Closes #73 trailer", errors)


if __name__ == "__main__":
    unittest.main()
