#!/usr/bin/env python3

import unittest

from validate_pr_body import validate


GOOD_BODY = """## How to Review

Read `internal/widget.go` first and verify failures remain closed.

## Summary

Adds the requested widget behavior without changing the public API.

## Testing

- `go test ./...` — passed

## Example Usage

```yaml
widget: enabled
```

Closes #73
"""


class ValidatePRBodyTest(unittest.TestCase):
    def test_accepts_complete_body(self) -> None:
        self.assertEqual(validate(GOOD_BODY, issue=73, require_example=True), [])

    def test_requires_core_sections(self) -> None:
        errors = validate("## Summary\n\nChange.\n")
        self.assertIn("expected exactly one ## How to Review heading", errors)
        self.assertIn("expected exactly one ## Testing heading", errors)

    def test_requires_core_section_order(self) -> None:
        body = "## Summary\n\nChange.\n## How to Review\n\nRead.\n## Testing\n\nPassed.\n"
        self.assertIn(
            "required sections must be ordered: How to Review, Summary, Testing",
            validate(body),
        )

    def test_requires_example_when_requested(self) -> None:
        body = GOOD_BODY.replace("## Example Usage\n\n```yaml\nwidget: enabled\n```\n\n", "")
        self.assertIn(
            "expected exactly one ## Example Usage heading",
            validate(body, require_example=True),
        )

    def test_rejects_ai_attribution(self) -> None:
        variants = (
            "<!-- CURSOR_SUMMARY -->",
            "Generated by Claude",
            "Generated using ChatGPT",
            "Co-authored-by: Codex <bot@example.com>",
            "Reviewed by Cursor Bugbot",
        )
        for variant in variants:
            with self.subTest(variant=variant):
                self.assertTrue(validate(f"{GOOD_BODY}\n{variant}\n"))

    def test_requires_exact_closing_trailer(self) -> None:
        errors = validate(GOOD_BODY.replace("Closes #73", "Fixes #73"), issue=73)
        self.assertIn("expected exactly one Closes #73 trailer", errors)


if __name__ == "__main__":
    unittest.main()
